apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: accountoptions-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: accountoptions
    spec:
      containers:
      - image: kristijanmirceta/birocloud-accountoptions:latest
        name: accountoptions
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-accountoptions:5432/accountoptions
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.13.134:32696
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP