apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-accountoptions-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-accountoptions
    spec:
      containers:
        - image: postgres:latest
          name: postgres-accountoptions
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: accountoptions
          ports:
          - containerPort: 5432
            protocol: TCP